### PR TITLE
Print swipe number for PingFederate

### PR DESCRIPTION
**Pull request by silver886**
Print swipe number if there is `div.numbermatching` in swipe page.

Fix https://github.com/Versent/saml2aws/issues/1114

### CODE REVIEW

**Comment by silver886** [comment]
@mapkon could we have this merged and released?
I also took a look at #877 and added unit test for it.

**Comment by mapkon** [comment]
> @mapkon could we have this merged and released? I also took a look at #877 and added unit test for it.

@silver886 Yes, that can be arranged. However, not with a decreased test coverage as it is now. You will have to bump that coverage up.

**Comment by silver886** [comment]
That's interesting.
`TestHandleSwipe` is added and should increase the coverage. 🤔

**Comment by mapkon** [comment]
> That's interesting. `TestHandleSwipe` is added and should increase the coverage. 🤔

The Test coverage report is above. Please check it out

**Comment by silver886** [comment]
I checked, and the report said it increases the coverage by `0.31%`.
And Codecov, https://app.codecov.io/gh/Versent/saml2aws/commit/46cab7e270159126a0ebd000906ed9a051a49d1e, also shows the same results.

**Comment by mapkon** [comment]
> I checked, and the report said it increases the coverage by `0.31%`. And Codecov, https://app.codecov.io/gh/Versent/saml2aws/commit/46cab7e270159126a0ebd000906ed9a051a49d1e, also shows the same results.

lol! I was referencing a cached version. My bad. I will take another look.

**Review by mapkon — APPROVED** [review]

**Comment by steven130169** [comment]
I need this feature, please release it. Thanks.

**Comment by mapkon** [comment]
> I need this feature, please release it. Thanks.

I am on it - been slightly busy

**Comment by mapkon** [comment]
I have cut the v2.36.11 Release

**Pull request merged**
