### PR TITLE
Fill CSRF token for PingFederate

### LINKED ISSUE #807: Pingfed fail when using OTP after swipe timeout
Attempting perform `saml2aws` flow with `pingfed`.

The OTP after swipe always failed.

OS: Windows 10 (19044.1645)
saml2aws version: 2.34.0

Verbose log (personal info censored):
```
time="2022-04-25T11:01:31+08:00" level=debug msg=Running command=login
time="2022-04-25T11:01:31+08:00" level=debug msg="Check if creds exist." command=login
time="2022-04-25T11:01:31+08:00" level=debug msg=Expand name="C:\\Users\\user/.aws/credentials" pkg=awsconfig
time="2022-04-25T11:01:31+08:00" level=debug msg=resolveSymlink name="C:\\Users\\user\\.aws\\credentials" pkg=awsconfig
time="2022-04-25T11:01:31+08:00" level=debug msg=ensureConfigExists filename="C:\\Users\\user\\.aws\\credentials" pkg=awsconfig
Using IdP Account saml-admin to access Ping https://login.example.com
To use saved password just hit enter.

? Username me@example.com
? Password

time="2022-04-25T11:01:33+08:00" level=debug msg="building provider" command=login idpAccount="account {\n  URL: https://login.example.com\n  Username: me@example.com\n  Provider: Ping\n  MFA: Auto\n  SkipVerify: false\n  AmazonWebservicesURN: urn:amazon:webservices\n  SessionDuration: 3600\n  Profile: saml-admin\n  RoleARN: arn:aws:iam::123456789012:role/admin-from-saml\n  Region: us-east-1\n}"
time="2022-04-25T11:01:33+08:00" level=debug msg="MFA Token expiry date:2022-04-22T10:05:12Z" Cache_file="C:/Users/user/.saml2aws/ping.saml" IdpAccount=saml-admin pkg=samlcache
time="2022-04-25T11:01:33+08:00" level=debug msg="Cache is invalid" command=login
Authenticating as me@example.com ...
time="2022-04-25T11:01:33+08:00" level=debug msg="HTTP Req" URL="https://login.example.com/idp/startSSO.ping?PartnerSpId=urn:amazon:webservices" http=client method=GET
time="2022-04-25T11:01:35+08:00" level=debug msg="HTTP Res" Status="401 Unauthorized" http=client
time="2022-04-25T11:01:35+08:00" level=debug msg="doc detect" provider=pingfed type=refresh
time="2022-04-25T11:01:35+08:00" level=debug msg="HTTP Req" URL="https://login.example.com/idp/startSSO.ping?PartnerSpId=urn:amazon:webservices" http=client method=GET
time="2022-04-25T11:01:38+08:00" level=debug msg="HTTP Res" Status="200 OK" http=client
time="2022-04-25T11:01:38+08:00" level=debug msg="doc detect" provider=pingfed type=login
time="2022-04-25T11:01:38+08:00" level=debug msg="HTTP Req" URL="https://login.example.com/idp/43AUZ_UuHhL/resumeSAML20/idp/startSSO.ping" http=client method=POST
time="2022-04-25T11:01:38+08:00" level=debug msg="HTTP Res" Status="200 OK" http=client
time="2022-04-25T11:01:38+08:00" level=debug msg="doc detect" provider=pingfed type=form-redirect
time="2022-04-25T11:01:38+08:00" level=debug msg="HTTP Req" URL="https://authenticator.pingone.com/pingid/ppm/auth" http=client method=POST
time="2022-04-25T11:01:40+08:00" level=debug msg="HTTP Res" Status="200 " http=client
time="2022-04-25T11:01:40+08:00" level=debug msg="doc detect" provider=pingfed type=webauthn
time="2022-04-25T11:01:40+08:00" level=debug msg="HTTP Req" URL="https://authenticator.pingone.com/pingid/ppm/auth" http=client method=POST
time="2022-04-25T11:01:40+08:00" level=debug msg="HTTP Res" Status="200 " http=client
time="2022-04-25T11:01:40+08:00" level=debug msg="doc detect" provider=pingfed type=swipe
time="2022-04-25T11:01:43+08:00" level=debug msg="HTTP Req" URL="https://authenticator.pingone.com/pingid/ppm/auth/status" http=client method=GET
time="2022-04-25T11:01:43+08:00" level=debug msg="HTTP Res" Status="200 " http=client
time="2022-04-25T11:01:46+08:00" level=debug msg="HTTP Req" URL="https://authenticator.pingone.com/pingid/ppm/auth/status" http=client method=GET
time="2022-04-25T11:01:47+08:00" level=debug msg="HTTP Res" Status="200 " http=client
time="2022-04-25T11:01:50+08:00" level=debug msg="HTTP Req" URL="https://authenticator.pingone.com/pingid/ppm/auth/status" http=client method=GET
time="2022-04-25T11:01:51+08:00" level=debug msg="HTTP Res" Status="200 " http=client
time="2022-04-25T11:01:54+08:00" level=debug msg="HTTP Req" URL="https://authenticator.pingone.com/pingid/ppm/auth/status" http=client method=GET
time="2022-04-25T11:01:55+08:00" level=debug msg="HTTP Res" Status="200 " http=client
time="2022-04-25T11:01:58+08:00" level=debug msg="HTTP Req" URL="https://authenticator.pingone.com/pingid/ppm/auth/status" http=client method=GET
time="2022-04-25T11:01:58+08:00" level=debug msg="HTTP Res" Status="200 " http=client
time="2022-04-25T11:02:01+08:00" level=debug msg="HTTP Req" URL="https://authenticator.pingone.com/pingid/ppm/auth/status" http=client method=GET
time="2022-04-25T11:02:02+08:00" level=debug msg="HTTP Res" Status="200 " http=client
time="2022-04-25T11:02:05+08:00" level=debug msg="HTTP Req" URL="https://authenticator.pingone.com/pingid/ppm/auth/status" http=client method=GET
time="2022-04-25T11:02:06+08:00" level=debug msg="HTTP Res" Status="200 " http=client
time="2022-04-25T11:02:06+08:00" level=debug msg="HTTP Req" URL="https://authenticator.pingone.com/pingid/ppm/auth/response" http=client method=GET
time="2022-04-25T11:02:06+08:00" level=debug msg="HTTP Res" Status="200 " http=client
time="2022-04-25T11:02:06+08:00" level=debug msg="doc detect" provider=pingfed type=otp
? Enter passcode 610347
time="2022-04-25T11:02:39+08:00" level=debug msg="HTTP Req" URL="https://authenticator.pingone.com/pingid/ppm/auth/otp" http=client method=POST
time="2022-04-25T11:02:40+08:00" level=debug msg="HTTP Res" Status="200 " http=client
time="2022-04-25T11:02:40+08:00" level=debug msg="Unknown document type" doc="<!DOCTYPE html><html><head>\n\t<title></title>\n\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\n\t<meta name=\"format-detection\" content=\"telephone=no\"/>\n\t<meta http-equiv=\"x-ua-compatible\" content=\"IE=edge\"/>\n\t<link rel=\"stylesheet\" href=\"/pingid/assets/css/main-v22.117.css\" media=\"screen\" title=\"no title\" charset=\"utf-8\"/>\n\t<link rel=\"stylesheet\" media=\"screen\" type=\"text/css\" href=\"/pingid/assets/css/jsdisabled.css\"/>\n\t \n\t<script type=\"text/javascript\" src=\"/pingid/assets/js/jquery-3.5.1.min.js\" onload=\"window.$ == null ? window.$ = window.jQuery = module.exports : null\"></script>\n\t<script type=\"text/javascript\" src=\"/pingid/assets/js/jquery-migrate-3.3.0.min.js\"></script>\n    <script type=\"text/javascript\" src=\"/pingid/assets/js/spin.js\"></script>\n\t<script type=\"text/javascript\" src=\"/pingid/assets/js/utils/iosWebClipsValidation.js\"></script>\n</head>\n<body>\n\t<noscript>\n    \n\n\n\n\n\n\n\n\n<!DOCTYPE html>\n<html>\n<head>\n\t<title></title>\n\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n\t<meta name = \"format-detection\" content = \"telephone=no\">\n\t<link rel=\"stylesheet\" href=\"/pingid/assets/css/jsdisabled.css\" media=\"screen\" title=\"no title\" charset=\"utf-8\">\n</head>\n<body>\n    <div class=\"nojspage dialog\">\n            \n\n            <div class=\"window error\">\n                <div class=\"content\">\n                    <div class=\"status\"></div>\n        \t\t\t<div class=\"title-text\">\n        \t\t\t    Important\n                    </div>\n\n        \t            <div class=\"error-text\">\n        \t\t\t\t\t<div class=\"text\">\n        \t\t\t\t\t    PingID requires Javascript to be enabled. If the problem persists, please contact your administrator.\n        \t\t\t\t\t</div>\n        \t            </div>\n\n                </div>\n            </div>\n\n            <div class=\"admin-message\" /><!-- admin message pushes footer to the bottom of the page -->\n\n            <div class=\"footer\">\n                <div class=\"pingid_logo\"></div>\n                <div class=\"copyright\">\n                    Copyright &copy; 2003-2022 Ping Identity Corporation. All rights reserved.\n                </div>\n            </div>\n    </div>\n</body>\n</html>\n\t   <style type=\"text/css\">\n\t\t\t.dialog { display:none; }\n\t\t</style>\n\t</noscript>\n    <div class=\"dialog\">\n       \t\t\n\t\n    \n    \n\n    <div class=\"window error single-device\">\n        <div class=\"content\">\n            <div class=\"status\"></div>\n\t\t\t<div class=\"title-text\">\n                Error\n            </div>\n\t\t\t\n\t            <div class=\"error-text\">\n\t\t\t\t\t<div class=\"text\">\n\t\t\t\t    \tError occurred during authentication with PingID. Try again.\n\t\t\t\t\t</div>\n\t            </div>\n\t\t\t\n\n\n            <form method=\"post\" action=\"\" id=\"form1\">\n\t\t\t\t\n\t\t\t\t\t<input name=\"ppm_response\" type=\"hidden\" id=\"ppm_response\" value=\"\"/>\n\t\t\t\t\n\n\t\t\t\t\n\n\n\t\t\t\t<div class=\"buttons\">\n\t\t\t\t\t\t\n\t                    \n\t\t\t\t\t\t\n\t\t\t\t\t</div>\n            </form>\n\t\t\t\n        </div>\n    </div>\n    <div class=\"admin-message\">\n        \n    </div>\n\n\n    <div class=\"footer\">\n        <div class=\"logo\"></div>\n        <div class=\"copyright\">\n            Copyright © 2003-2022 Ping Identity Corporation. All rights reserved.\n        </div>\n    </div>\n\n    </div>\n\n\n</body></html>" provider=pingfed
Unknown document type
Error authenticating to IdP.
```

Root cause might be the CSRF token is not presented in the OTP form.

### PR DESCRIPTION
**Pull request by silver886**
Fill CSRF token from cookies for `pingfed` in `handleOTP` to fix OTP fail.

Also change the `goquery` document creation from `Reader`(res.Body) to `Response`(res)

Fix #807

### CODE REVIEW

**Review by mapkon — CHANGES_REQUESTED** [review]
@silver886 I would like to merge this in preparation for the upcoming release. Could you take a look at the lint errors and fix them?

Please consider adding tests since the new branch will certainly affect the code coverage

**Comment by silver886** [comment]
This PR uses the deprecated method `goquery.NewDocumentFromResponse` to get request URL.
I can change it back to `goquery.NewDocumentFromReader` but it would require an additional argument to pass URL information.
I will update the codebase later with no deprecated methods and add unit test for it.

**Comment by mapkon** [comment]
> This PR uses the deprecated method `goquery.NewDocumentFromResponse` to get request URL. I can change it back to `goquery.NewDocumentFromReader` but it would require an additional argument to pass URL information. I will update the codebase later with no deprecated methods and add unit test for it.

Great! Thanks - and looking forward to it.

**Comment by silver886** [comment]
I pushed the commits.
But it seems like `./pkg/provider/browser/browser_test.go` couldn't pass the unit test.
I think there is no shared code was modified in the PR . . .

**Review by mapkon — CHANGES_REQUESTED** [review]
The code coverage has gone down. This will cause the build to fail if merged as-is.

**Comment by silver886** [comment]
After this commit, coverage in `make test` increased 2%.
Hope this would make Codecov Report pass.

**Review by mapkon — APPROVED** [review]
Yes, that looks fine. Thank you.

**Pull request merged**
