### PR TITLE
Browser provider - Autofill works with more authentication forms

### PR DESCRIPTION
**Pull request by vjeantet**
Hello, 

This PR proposition updates the way the autofill func submits the form:
Instead of locating the submit button and clicking on it, it send an Enter keypress.

I had to implement this to make it works with my company authentification web form, which has no html submit button, but an image with javascript events linked to it.

### CODE REVIEW

**Review by mapkon — COMMENTED** [review]
Thank you for this PR.

However, aren't we making the implicit assumption that the page will have a submit button as a default or primary that responds to the enter click event? What happens if it is not?

**Comment by vjeantet** [comment]
Hello, That won't work.

I can suggest something that covers all cases:

WHEN the input[type="submit"] exists, THEN click on it.
WHEN the input[type="submit"] does not exist THEN press ENTER.

**Comment by mapkon** [comment]
> Hello, That won't work.
> 
> I can suggest something that covers all cases:
> 
> WHEN the input[type="submit"] exists, THEN click on it. WHEN the input[type="submit"] does not exist THEN press ENTER.

Sounds much more resilient. If you don't mind, please add some tests to hasten the reviews.

**Comment by vjeantet** [comment]
updated to handle the two cases, with tests.

**Review by mapkon — APPROVED** [review]

**Pull request merged**
