### PR TITLE
Fix Okta MFA regression issue

### PR DESCRIPTION
**Pull request by alsmola**
I tested this and it fixed https://github.com/Versent/saml2aws/issues/382 for me

Since the page for MFA in Okta desn't contain `form[action=\"https://signin.aws.amazon.com/saml\"]"` in `docIsFormRedirectToAWS`, the whole `if` block is skipped and we get the `Unknown document type` error.

This moves the MFA requesting code outside of that check so that it's hit if none of the other conditions are met.

### CODE REVIEW

**Comment by Anton0** [comment]
Thanks for doing this, I've pulled your branch and tested and this fix works.

I was going to add a test to the response to check if it was the app level MFA prompt rather than doing it as a general catch all but I think in the interest of getting things working again we should merge this fix.

**Comment by alsmola** [comment]
Any updates here @Anton0? Who needs to approve for us to merge?

**Comment by alsmola** [comment]
As a heads up I have a branch that supports WebAuthn once this merges: https://github.com/alsmola/saml2aws/pull/1

**Comment by alsmola** [comment]
@wolfeidau thanks! Any idea when you'll push a new version? Hoping to release this to my company soon and would love to let people use the default install instructions.

**Pull request merged**
