### PR TITLE
feat(storage) Keychain storage for password.

### PR DESCRIPTION
**Pull request by wolfeidau**
* Refactor all login related flags.
* Added role command line option

### CODE REVIEW

**Comment by hoegertn** [comment]
LGTM but maybe you have a look at how I implemented the role switch and see if you can take some ideas. Especially, the role selection in the login method.

**Comment by wolfeidau** [comment]
@hoegertn Thanks a lot you highlighted a case I had missed and proposed a better name for the flag.

**Comment by hoegertn** [comment]
:+1: looks good. You can reject my PR then.

**Comment by hoegertn** [comment]
Do you plan to release a new version? I have customers waiting for the role and TLS fix.

**Comment by wolfeidau** [comment]
I have built a release and published it, going to do a bit more testing across all providers tomorrow (Australian time) then update the homebrew tap. Any help testing would be appreciated :)

Cheers

**Pull request merged**
