### PR TITLE
removing osx build

### PR DESCRIPTION
**Pull request by debojitkakoti**
There is error on osx build

### CODE REVIEW

**Comment by debojitkakoti** [comment]
This is related to issue [https://github.com/Versent/saml2aws/issues/56](url)

**Comment by cliff-wakefield** [comment]
Why remove the OS X build?

If there was an error with the build it needs fixing, not removing.

Anyway it builds fine for me on OS X.

**Comment by rdkls** [comment]
> There is error on osx build

I and plenty of my friends use it on OSX @debojitkakoti !
And it works!
Please can you close the PR against the main repo?
If you personally want to not build OSX, please just modify your local copy.
Thank you 🙏

**Comment by wolfeidau** [comment]
If you need to install locally you can use `make install` on linux.

**Pull request closed without merging**
