### PR TITLE
Okta MFA - Support multiple of same type

### PR DESCRIPTION
**Pull request by szechyjs**
This resolves the linting issues in #745 since its has gone stale (abandoned?).

### CODE REVIEW

**Comment by szechyjs** [comment]
cc: @QuentinBtd @wolfeidau @rarruda

**Comment by gliptak** [comment]
@mapkon please approve workflow run

**Comment by mapkon** [comment]
> @mapkon please approve workflow run

Done!

**Comment by szechyjs** [comment]
Any chance of this getting merged soon?

**Comment by mapkon** [comment]
> Any chance of this getting merged soon?

I could merge it if you can help me with write some unit tests, especially given that the method signature for `parseMfaIdentifer` has changed.

**Comment by mapkon** [comment]
@szechyjs Any chance you could add tests to this PR?

**Comment by mapkon** [comment]
> > @szechyjs Any chance you could add tests to this PR?
> 
> @mapkon I added a few test for the modified `parseMfaIdentifer` method.

You are a legend! I will take a look and merge soonest.

**Pull request merged**
