### PR TITLE
[KeyCloak] Customizable password error validator

### PR DESCRIPTION
**Pull request by kenjikikuchi**
This PR is for the issue [#1265](https://github.com/Versent/saml2aws/issues/1265). Thank you!

### CODE REVIEW

**Comment by mapkon** [comment]
@kenjikikuchi This looks good and is excellent. Thank you for taking the time to implement it. 

Any chance you have bandwidth to add some tests

**Comment by kenjikikuchi** [comment]
Thank you for looking into my PR. On it!

**Comment by kenjikikuchi** [comment]
Hi @mapkon, I have added some tests for this change, but screwed up with git rebase. I opened a new PR. Please take a look at https://github.com/Versent/saml2aws/pull/1275. In the PR #1275, parameter examples are also added to Readme. I want to close this #1268. Thank you.

**Comment by mapkon** [comment]
Closing as #1275 covers this

**Pull request closed without merging**
