### PR TITLE
Fix Okta WebAuthn challenge

### PR DESCRIPTION
**Pull request by anothertobi**
PR #1039 introduced a change to okta_webauthn.go that most probably
is a relic from the development phase of the Duo integration (ref:
82b3ba36c28b94c0138e874177b830b08c1468bb).

Since the Duo integration implements its own ChallengeU2F, this should
be safe to revert.

### CODE REVIEW

**Comment by anothertobi** [comment]
Verified that this fixes Okta + WebAuthn using a YubiKey. Would be great if someone with Okta + Duo could double-check that this indeed doesn't break their setup (maybe @lizduty / @6f6d6172 ?).

**Comment by smlx** [comment]
I can confirm this fixes Okta U2F authentication for me.

**Comment by satyamab** [comment]
Thank you for fixing this! Also confirming that this fixes Okta U2F authentication for me. The impact is quite widespread for our eng team. Any idea when a release may be available for this fix? 🙏

**Comment by dasrecht** [comment]
Can also confirm this fix works as expected - Thanks @anothertobi!

**Comment by lizduty** [comment]
confirmed this doesn't break my workflow

**Comment by smlx** [comment]
@anothertobi any chance you could take a look at the test failure? :slightly_smiling_face:

**Comment by anothertobi** [comment]
> @anothertobi any chance you could take a look at the test failure? 🙂

68806fe1ba9c0c64cdf11e771c220eb6c523a4f2 seems to have fixed the build, but the linter is timing out. Locally this runs through in < 1s 🤔

**Comment by anothertobi** [comment]
Rebased the branch and #1074 did fix the golangci-lint timeout we had earlier.

**Comment by roptoor** [comment]
Curious what more is needed to get this merged, as it seems to be affecting quite a few users?

**Comment by jmandel1027** [comment]
Heyyo, would it be possible to cut a new release with this patch? It looks like this is still affecting a large number of folks in our eng org too

**Comment by mapkon** [comment]
Yeah, we would need to test the current code for release readiness. If you volunteer to coordinate that, I would very much appreciate it

**Comment by anothertobi** [comment]
@szechyjs this PR is included in the [v2.36.10](https://github.com/Versent/saml2aws/releases/tag/v2.36.10) release.

**Pull request merged**
