### PR TITLE
fix: find the chosen okta mfa option in the mfaOptions

### PR DESCRIPTION
**Pull request by russell**
find the index of the a duoMfaOption by looking in the duoMfaOptions.

the duoMfaOptions is dynamically created, so it could have any number of items, the reason that using the interactively  selected mechanism works is that it's choosing based on the list of duoMfaOptions options rather than hardcoded ids.  This change does something similar, but searches through duoMfaOptions to find the option passed at the CLI, if the item is missing, then an error will be emitted.

for example if I don't have passcode enabled and if i try to force that option
```
$ ./saml2aws login --session-duration=43200 --mfa='DUO' --duo-mfa-option='Passcode' --skip-prompt --force --role='arn:aws:iam::183823948234:role/okta/team'
Using IdP Account default to access Okta https://foobar.okta.com/app/amazon_aws/aoeusnthoaenuth/sso/saml
Authenticating as rsim@foobar.com ...
Error authenticating to IdP.: error verifying MFA: error unsupported MFA option 'Passcode'
```

fixes https://github.com/Versent/saml2aws/issues/1079 https://github.com/Versent/saml2aws/issues/1061

### CODE REVIEW

**Review by mapkon — CHANGES_REQUESTED** [review]
Hey - do you mind adding tests to this? This is going to push the coverage down and make the build to fail

**Comment by russell** [comment]
Sure! here is a test, can you give me some feedback about the fixtures, i haven't trimmed them down to only the fields that are referenced in the okta.go calls, if you like i can do that.  I left them with more information rather than less in the hope that future readers would be able to improve the logic without needing access to fresh raw responses from duo.  But each to their own, would you like them trimmed?

**Review by mapkon — APPROVED** [review]

**Comment by mapkon** [comment]
> Sure! here is a test. Can you give me some feedback about the fixtures, i haven't trimmed them down to only the fields that are referenced in the okta.go calls, if you like i can do that. I left them with more information rather than less in the hope that future readers would be able to improve the logic without needing access to fresh raw responses from duo. But each to their own, would you like them trimmed?

I personally think we should trim them down so that the test is focused on what it is testing. The extra context can be confusing.

@gliptak thoughts?

**Comment by russell** [comment]
> I personally think we should trim them down so that the test is focused on what it is testing. The extra context can be confusing.

i'm cool with doing that, i'll update the PR later today.  I'm a bit on the fence personally so it's not a big deal

**Comment by russell** [comment]
ok, this is ready for review again, I have extended the test suite to assert all the server request's and trimmed down the fixtures

**Review by mapkon — APPROVED** [review]

**Comment by mapkon** [comment]
@russell  This has been released

**Pull request merged**
