### PR TITLE
(copy) Add minimal Dockerfile and a goreleaser docker config

### PR DESCRIPTION
**Pull request by gliptak**
https://github.com/gliptak/saml2aws/actions/runs/5009684628

Docker image published

https://github.com/gliptak/saml2aws/pkgs/container/saml2aws

### CODE REVIEW

**Comment by gliptak** [comment]
https://github.com/softprops/action-gh-release/issues/232

**Comment by gliptak** [comment]
@mapkon the lint error seem to be intermittent

**Comment by mapkon** [comment]
It would appear so, which is a shame. I experienced these failures last week

**Comment by mapkon** [comment]
@gliptak Is it fixed?

**Comment by gliptak** [comment]
@mapkon release workflow is green (i haven't made updates re. intermittent lint failure)

**Review by mapkon — APPROVED** [review]

**Comment by mapkon** [comment]
@gliptak Are you happy if I merge this?

**Pull request merged**
