### PR TITLE
Add 5m timeout to page.WaitForRequest

### PR DESCRIPTION
**Pull request by kbarlowgw**
I didn't see an appropriate place to add/update a unit test for this but I have been using it locally and it fixes the issue.  Doesn't seem like an external configuration flag is required but may be if users continue to have issues.

### CODE REVIEW

**Comment by mapkon** [comment]
@kbarlowgw How about `browser_test.go`?

I think you need find a way for this path `playwright.PageWaitForRequestOptions{Timeout: &timeout}` to be exercised so that test coverage is not affected.

**Comment by kbarlowgw** [comment]
Thanks... I pushed an update that will hopefully fix it.  It went from
46.7% to 48.9% locally:

ok   github.com/versent/saml2aws/v2/pkg/provider/browser 1.935s coverage:
48.9% of statements

Please let me know if there's anything else required.

Keith

**Review by mapkon — APPROVED** [review]

**Comment by alediaferia** [comment]
Any chance this could be made configurable via e.g. command line switch?

**Comment by kbarlowgw** [comment]
I can look into that.

Keith

**Comment by kbarlowgw** [comment]
It looks to me that the existing timeout field in the account settings was
unused in browser configurations so I mapped that to the timeout for
Page.WaitForRequest.  If the timeout is set less than 30s, the default of 5
mins will be used.  It seems pointless to allow timeouts less than the
default provided by playwright.  Unit tests have been added & updated.

Keith

**Comment by kbarlowgw** [comment]
Thanks, all!

Keith

**Comment by dkimdon** [comment]
This change works great for me.  What needs to happen to get this in the next release?

**Comment by mapkon** [comment]
I just need to cut a release. I am looking to a window to do that

**Pull request merged**
