### PR TITLE
Allow password to be saved to keychain with skip-prompt

### LINKED ISSUE #485: [Mac] Putting password on command line configure isn't stored in keychain
I was trying to setup a complete account via the command line.

```saml2aws configure --idp-account=test  --idp-provider=JumpCloud --username=gbonk@github.com --password="abc123" --url="https://sso.jumpcloud.com/saml2/github" --profile=default --session-duration=28800 --mfa=Auto --skip-prompt```

The command succeeds but the MacOs Keychain does not have the password stored in it.

### PR DESCRIPTION
**Pull request by casperbiering**
Currently when you run the configure, the password is only saved to keychain if you don't specify the `--skip-prompt` argument.

We use saml2aws as the last command in a setup script, where it doesn't make sense to prompt the user to re-enter the same data.

Fixes #485.

### CODE REVIEW

**Comment by jpetrucciani** [comment]
This would fix #485, correct?

**Comment by casperbiering** [comment]
Yes it would

**Comment by cvoege** [comment]
@wolfeidau think we could get this merged and release? would be a big help to my team!

**Comment by benaduggan** [comment]
bump, I'm also waiting for this to resolve some issues within my org!

**Comment by sledigabel** [comment]
This would be a great help during onboarding 👍

**Comment by wolfeidau** [comment]
The main concern i have with this code is the nested if / if else's it is pretty hard to read now 😞

**Comment by casperbiering** [comment]
@wolfeidau I've refactored the password prompting. Please take another look.

**Comment by snoe925** [comment]
@wolfeidau can you evaluate this again?  It's a nice feature I'd like to have.

**Comment by casperbiering** [comment]
Hi @wolfeidau, can you please take another look.

**Comment by benyitzhaki** [comment]
@wolfeidau kindly pinging :) we are also having issues with this, would be great to have this merged

**Review by mapkon — APPROVED** [review]
@wolfeidau Do you still have concerns about the code? I would like to merge this

**Comment by mapkon** [comment]
@gliptak

**Comment by lmottaca-te** [comment]
Bump, my organisation also has an interest in seeing this merged.

**Comment by mapkon** [comment]
@lmottaca-te That is good. Unfortunately, this will bump the coverage down, so I will need it to be accompanied with tests. If you are willing to add tests, I can work with you to merge it.

**Comment by casperbiering** [comment]
Since creating the PR my organisation has moved to AWS SSO, so unfortunately I don't have the time to add the tests. Feel free to fork my branch or let me know if you want to be added as a collaborator on my fork/repo.

**Comment by mapkon** [comment]
@lmottaca-te Will you help implement tests for this? If not, I am inclined to close the PR

**Comment by tinaboyce** [comment]
@mapkon I have added tests which has resulted in a positive coverage https://app.codecov.io/gh/Versent/saml2aws/pull/547 . Is this enough for the PR to proceed?

**Review by mapkon — APPROVED** [review]
@tinaboyce Should be ok? Let me take a deeper look

**Comment by tinaboyce** [comment]
FYI, updated the test to utilise defer as I forgot it was a thing.

**Pull request merged**
