### PR TITLE
fix: enable cgo on macos builds

### LINKED ISSUE #900: release not creating keychain secret
Hello,

if I directly use the latest release 
saml2aws_2.36.1_darwin_arm64.tar.gz 
saml2aws does not create a keychain secret **saml2aws Credentials**

If I use the forumla https://formulae.brew.sh/formula/saml2aws

```
brew install saml2aws
saml2aws --version   
2.36.1
```

the secret is created just fine.

You can reproduce this when going through a login with both versions and check for the keychain secrets:

```sh
saml2aws login
```

### PR DESCRIPTION
**Pull request by Meroje**
just like it's done on https://github.com/Versent/saml2aws/blob/master/.goreleaser.ubuntu-20.04.yml#L23-L24

fixes #900 #873

### CODE REVIEW

**Review by mapkon — APPROVED** [review]

**Comment by jycamier** [comment]
@mapkon is it possible to re-release macos releases ?

**Comment by mapkon** [comment]
Sure, I will attempt that tomorrow.

Mark

**Comment by mapkon** [comment]
> @mapkon is it possible to re-release macos releases ?

Done!

**Comment by jycamier** [comment]
Thank you !

**Pull request merged**
