### PR TITLE
Unit test for Support Number Challenge for Okta MFA (#877)

### PR DESCRIPTION
**Pull request by silver886**
Unit test for #877.

https://github.com/Versent/saml2aws/pull/877#issuecomment-1691441024
https://github.com/Versent/saml2aws/pull/877#issuecomment-1692616237

### CODE REVIEW

**Comment by silver886** [comment]
This PR won't pass unit test unless #877 is in place.

**Comment by mapkon** [comment]
@silver886 The tests are failing on this one.

**Comment by silver886** [comment]
Yeah, because the actual code that implements the feature is #877.

Should I copy @muramasa64 's code into this PR?

**Comment by mapkon** [comment]
> Yeah, because the actual code that implements the feature is #877.
> 
> Should I copy @muramasa64 's code into this PR?

Yeah - and probably close that PR since it will no longer be required.

**Pull request merged**
