### PR TITLE
[#895] Changed default behaviour for credential-process

### PR DESCRIPTION
**Pull request by BEllis**
--credential-process now implicitly sets quiet and skip-prompt and will no longer save to ~/.aws/credentials

This prevents the need to set --quiet --skip-prompt and --credentials-file arguments for awscli to work correctly with saml2aws as credentials provider.

### CODE REVIEW

**Comment by BEllis** [comment]
Relates to #895

**Comment by lidall** [comment]
Hi, will this change ensure auto-updating of .aws/credential file?
I am struggling a lot with this issue today

**Review by mapkon — COMMENTED** [review]
@BEllis Do you mind taking a look at this and fixing the conflicts?

**Comment by BEllis** [comment]
> @BEllis Do you mind taking a look at this and fixing the conflicts?

@mapkon  Done.

**Comment by mapkon** [comment]
Ooof! If we merge this, the build will fail due to reduce code coverage. Mind rolling a few tests?

**Pull request merged**
