### PR TITLE
onelogin: use the /api/2/saml_assertion API

### PR DESCRIPTION
**Pull request by rodmatos**
Replaces the use of the /api/1/saml_assertion with its successor.
OneLogin has communicated that the /api/1/saml_assertion has been
deprecated and should have been removed in Feb 2021.
Fixes issue #778.

[Documentation for the /1/saml_assertion](https://developers.onelogin.com/api-docs/1/saml-assertions/generate-saml-assertion).
[Documentation for the new /2/saml_assertion](https://developers.onelogin.com/api-docs/2/saml-assertions/generate-saml-assertion).

### CODE REVIEW

**Comment by marcus-crane** [comment]
This seems kind of important! 😬 Thanks

**Comment by marcus-crane** [comment]
@wolfeidau

**Comment by narcistesa** [comment]
Any chance of getting this reviewed/merged? 🙏

**Comment by rodmatos** [comment]
@wolfeidau: sorry for the direct ping but any chance of getting this pull request reviewed?

**Comment by ElementSpanky** [comment]
This is pestering us as well, hopefully it'll get reviewed and merged soon!

**Pull request merged**
