### PR TITLE
Handle extra "Send text message" challenge page

### PR DESCRIPTION
**Pull request by edwardrf**
It seems some times google will present an extra "Send text message" challenge page that requires the user to click on the button to actually get text message sent and present the code input in the next page.

#1137

### CODE REVIEW

**Comment by lionello** [comment]
@mapkon  can you check?

**Comment by mapkon** [comment]
> @mapkon can you check?

@edwardrf Thank you for these changes. Do you mind adding some tests to this?

**Comment by edwardrf** [comment]
@mapkon sorry for the delay, just added the test case, plz take a look.

**Comment by edwardrf** [comment]
@mapkon i've updated the test case that wasn't functioning correctly due to automatic html formatting, plz take a look again.

**Comment by mapkon** [comment]
> @mapkon i've updated the test case that wasn't functioning correctly due to automatic html formatting, plz take a look again.

Thanks buddy! I will take a look

**Pull request merged**
