### PR TITLE
Base default AWS credentials path on USERPROFILE

### PR DESCRIPTION
**Pull request by mberginbh**
Proposed fix for #135

### CODE REVIEW

**Comment by wolfeidau** [comment]
I had a look in the upstream library and it looks like it is already doing this check.

https://github.com/mitchellh/go-homedir/blob/b8bc1bf767474819792c23f32d8286a45736f1c6/homedir.go#L120-L137

There is a PR open to refactor it a bit https://github.com/mitchellh/go-homedir/pull/19

**Comment by mberginbh** [comment]
Upstream has slightly different logic when %HOMEDRIVE% and %HOMEDIR% are set, resulting in inconsistency with awscli in this case. On my system both these and %USERPROFILE% are set, and so awscli and saml2aws have a different idea about where the config file is.

**Comment by sasmithCalpoly** [comment]
Please merge the pull request ASAP. 

The AWS documentation at : https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html
specifies that the default location for .aws on windows is: dir "%UserProfile%\.aws"

Without this being fixed, Windows users with a Home drive mapped will have the saml2aws program putting the .aws\credentials file in the wrong place from where all AWS CLI commands expect the file to be located.

**Comment by vacovsky** [comment]
I fixed the merge conflicts with this PR in a new PR: https://github.com/Versent/saml2aws/pull/270

**Comment by wolfeidau** [comment]
:+1: merged as above.

**Pull request closed without merging**
