### PR TITLE
Add support for using DUO Trusted Device certificate validation

### PR DESCRIPTION
**Pull request by ctennis**
Duo has a feature that allows you to validate the endpoint being used is trusted when doing push notifications.  If this is enabled, it adds a certificate check requirement on your device to validate against a known certificate that was pushed to your device's cert store.

This PR adds flow such that if the web response includes this validation, we perform it as some additional steps (which is required, or the push notification will not occur).

This should be no change to the existing flow for those without this feature enabled.

### CODE REVIEW

**Comment by 6f6d6172** [comment]
Just dropping a +1 here -- we're deploying Trusted Endpoints via Duo and it looks like your other fork (`ct/dtd5`) is capable of handling it just fine, not to mention with added support for u2f tokens. 

@mapkon besides getting the PR rebased/merge conflicts resolved, is there anything else needed to get this merged? I suspect users running into issues like #678 are also affected. @ctennis has already done the heavy lifting, it would be a shame to let that work languish in a fork all on its own. I'd be happy to help any way I can.

**Comment by mapkon** [comment]
> Just dropping a +1 here -- we're deploying Trusted Endpoints via Duo and it looks like your other branch (`ct/dtd5`) is capable of handling it just fine, not to mention with added support for u2f tokens.
> 
> @mapkon besides getting the PR rebased/merge conflicts resolved, is there anything else needed to get this merged? I suspect users running into issues like #678 are also affected. @ctennis has already done the heavy lifting, it would be a shame to let that work languish in a fork all on its own. I'd be happy to help any way I can.

As long as the PR is rebased, tested and does not bump code coverage down, I am happy to merge it. Let me know when it's ready

**Comment by ctennis** [comment]
You're more than welcome to have this code, or make a new PR based off of it.  We had to use this fork for the past 18 months, but now that we've moved to Okta Verify, saml2aws doesn't work at all for us anymore, so we're not using the project now.

**Comment by mapkon** [comment]
Please see #1027

**Pull request closed without merging**
