### PR TITLE
Fix GoogleApps Login

### PR DESCRIPTION
**Pull request by falms**
### details:
Recently there was a small change to the Google Workspace (`provider=GoogleApps`) login form.
The value `challengeId` was changed from `1` to `2` on my account.

This PR changes the handling form data.
- use form data returned by server instead of hard-coded values

Fixes: #933 

### tested cases:
| | v2.35.0 | v2.36.2 | this PR |
|-|---------|--------|--------|
| my account (challengeId=2, Google Prompt) | Not Tested | NG | OK |
| co-worker's account (challengeId=1, TOTP) | OK | OK | OK |

### notes:
I cannot test this change enough, because I have no Google account which uses "Login page v1".
However, I think v1 is no longer available.

### CODE REVIEW

**Comment by jamesyale** [comment]
Before: 

```
Error authenticating to IdP.: page is missing saml assertion
```

After: 
```
Your new access key pair has been stored in the AWS configuration.
```

Works for me, thanks 👍

**Comment by 0rax** [comment]
Confirmed working on my end too :+1:

**Comment by mapkon** [comment]
@falms @0rax I will take a look at this probably end of this week or early next week

**Comment by mapkon** [comment]
@falms This looks fine. Would you be kind enough to add some unit tests?

**Review by wolfeidau — APPROVED** [review]
👍🏻

**Comment by mapkon** [comment]
@falms Let me know when the tests are ready. I will merge this then!

**Comment by falms** [comment]
@mapkon Thank you for your review! I want to add tests this weekend.

**Comment by falms** [comment]
@mapkon I added a few tests related to challenge id. Would you review this?

**Comment by amontalban** [comment]
@mapkon can you create a new tag so we can install this fix through Brew, please? Thanks!

**Comment by mapkon** [comment]
> @mapkon can you create a new tag so we can install this fix through Brew, please? Thanks!

@amontalban Yes, thank you for asking. I am preparing a release for EoW

**Comment by mapkon** [comment]
@amontalban Please take note: https://github.com/Versent/saml2aws/discussions/997

**Comment by amontalban** [comment]
> @amontalban Please take note: #997

Thank you very much!

**Pull request merged**
