### PR TITLE
Add Webauthn and Duo support for JumpCloud

### PR DESCRIPTION
**Pull request by logingood**
* Adds support of devices like Yubikey via [WebAuthn ](https://fidoalliance.org/fido2/fido2-web-authentication-webauthn/)
* Adds support of [Duo 2fa](https://duo.com/) authentication 

should address #390 

- Copied some code from Okta with modifications, works with Yubikey
- Inspired by https://github.com/Versent/saml2aws/pull/489 
- Tested all three (TOTP, Duo and Yubikey) seems to be working.

Menu looks like that 
image

And here is similar to Okta FIDO prompt to press flashing key.

image

Duo auth menu similar to Okta
image

### CODE REVIEW

**Comment by ahrenstein** [comment]
I can't seem to get this working. I think JumpCloud (or Duo) changed something recently

```
Pushed a login request to your device...
Success. Logging you in...
Response did not contain a valid SAML assertion
Please check your username and password is correct
To see the output follow the instructions in https://github.com/versent/saml2aws#debugging-issues-with-idps
```

Longer log using `saml2aws login --verbose`

```
 $ ./saml2aws login --verbose
DEBU[0000] Running                                       command=login
DEBU[0000] check if Creds Exist                          command=login
DEBU[0000] Expand                                        name=/Users/ahrenstein/.aws/credentials pkg=awsconfig
DEBU[0000] resolveSymlink                                name=/Users/ahrenstein/.aws/credentials pkg=awsconfig
DEBU[0000] ensureConfigExists                            filename=/Users/ahrenstein/.aws/credentials pkg=awsconfig
Using IDP Account default to access JumpCloud https://sso.jumpcloud.com/saml2/mainaws
DEBU[0000] Get credentials                               helper=osxkeychain serverURL="https://sso.jumpcloud.com/saml2/mainaws"
DEBU[0004] Get credentials                               helper=osxkeychain user=[REDACTED]
To use saved password just hit enter.
? Username 
? Password 

DEBU[0005] building provider                             command=login idpAccount="account {\n  URL: https://sso.jumpcloud.com/saml2/mainaws\n  Username: [REDACTED]\n  Provider: JumpCloud\n  MFA: Auto\n  SkipVerify: false\n  AmazonWebservicesURN: urn:amazon:webservices\n  SessionDuration: 28000\n  Profile: route\n  RoleARN: \n  Region: us-east-1\n}"
Authenticating as [REDACTED] ...
DEBU[0005] HTTP Req                                      URL="https://console.jumpcloud.com/userconsole/auth" http=client method=POST
DEBU[0006] HTTP Res                                      Status="401 Unauthorized" http=client
DEBU[0006] HTTP Req                                      URL="https://console.jumpcloud.com/userconsole/auth/duo" http=client method=GET
DEBU[0006] HTTP Res                                      Status="200 OK" http=client
DEBU[0006] HTTP Req                                      URL="https://[REDACTED].duosecurity.com/frame/web/v1/auth?tx=TX%[REDACTED]%[REDACTED]" http=client method=POST
DEBU[0007] HTTP Res                                      Status="200 OK" http=client
? Select a DUO MFA Option Duo Push
DEBU[0008] HTTP Req                                      URL="https://[REDACTED].duosecurity.com/frame/prompt" http=client method=POST
DEBU[0008] HTTP Res                                      Status="200 OK" http=client
DEBU[0008] HTTP Req                                      URL="https://[REDACTED].duosecurity.com/frame/status" http=client method=POST
DEBU[0008] HTTP Res                                      Status="200 OK" http=client
Pushed a login request to your device...
DEBU[0011] HTTP Req                                      URL="https://[REDACTED].duosecurity.com/frame/status" http=client method=POST
DEBU[0013] HTTP Res                                      Status="200 OK" http=client
Success. Logging you in...
DEBU[0013] HTTP Req                                      URL="https://[REDACTED].duosecurity.com/frame/status/[REDACTED]" http=client method=POST
DEBU[0013] HTTP Res                                      Status="200 OK" http=client
DEBU[0013] HTTP Req                                      URL="https://console.jumpcloud.com/userconsole/auth/duo" http=client method=POST
DEBU[0013] HTTP Res                                      Status="403 Forbidden" http=client
Response did not contain a valid SAML assertion
Please check your username and password is correct
To see the output follow the instructions in https://github.com/versent/saml2aws#debugging-issues-with-idps
```

**Comment by logingood** [comment]
> I can't seem to get this working. I think JumpCloud (or Duo) changed something recently as I did have another PR working with JumpCloud+Duo. Neither that PR's code nor this one's works.
> 
> ```
> Pushed a login request to your device...
> Success. Logging you in...
> Response did not contain a valid SAML assertion
> Please check your username and password is correct
> To see the output follow the instructions in https://github.com/versent/saml2aws#debugging-issues-with-idps
> ```
> 
> Longer log using `saml2aws login --verbose`
> 
> ```
>  $ ./saml2aws login --verbose
> DEBU[0000] Running                                       command=login
> DEBU[0000] check if Creds Exist                          command=login
> DEBU[0000] Expand                                        name=/Users/ahrenstein/.aws/credentials pkg=awsconfig
> DEBU[0000] resolveSymlink                                name=/Users/ahrenstein/.aws/credentials pkg=awsconfig
> DEBU[0000] ensureConfigExists                            filename=/Users/ahrenstein/.aws/credentials pkg=awsconfig
> Using IDP Account default to access JumpCloud https://sso.jumpcloud.com/saml2/mainaws
> DEBU[0000] Get credentials                               helper=osxkeychain serverURL="https://sso.jumpcloud.com/saml2/mainaws"
> DEBU[0004] Get credentials                               helper=osxkeychain user=[REDACTED]
> To use saved password just hit enter.
> ? Username 
> ? Password 
> 
> DEBU[0005] building provider                             command=login idpAccount="account {\n  URL: https://sso.jumpcloud.com/saml2/mainaws\n  Username: [REDACTED]\n  Provider: JumpCloud\n  MFA: Auto\n  SkipVerify: false\n  AmazonWebservicesURN: urn:amazon:webservices\n  SessionDuration: 28000\n  Profile: route\n  RoleARN: \n  Region: us-east-1\n}"
> Authenticating as [REDACTED] ...
> DEBU[0005] HTTP Req                                      URL="https://console.jumpcloud.com/userconsole/auth" http=client method=POST
> DEBU[0006] HTTP Res                                      Status="401 Unauthorized" http=client
> DEBU[0006] HTTP Req                                      URL="https://console.jumpcloud.com/userconsole/auth/duo" http=client method=GET
> DEBU[0006] HTTP Res                                      Status="200 OK" http=client
> DEBU[0006] HTTP Req                                      URL="https://[REDACTED].duosecurity.com/frame/web/v1/auth?tx=TX%[REDACTED]%[REDACTED]" http=client method=POST
> DEBU[0007] HTTP Res                                      Status="200 OK" http=client
> ? Select a DUO MFA Option Duo Push
> DEBU[0008] HTTP Req                                      URL="https://[REDACTED].duosecurity.com/frame/prompt" http=client method=POST
> DEBU[0008] HTTP Res                                      Status="200 OK" http=client
> DEBU[0008] HTTP Req                                      URL="https://[REDACTED].duosecurity.com/frame/status" http=client method=POST
> DEBU[0008] HTTP Res                                      Status="200 OK" http=client
> Pushed a login request to your device...
> DEBU[0011] HTTP Req                                      URL="https://[REDACTED].duosecurity.com/frame/status" http=client method=POST
> DEBU[0013] HTTP Res                                      Status="200 OK" http=client
> Success. Logging you in...
> DEBU[0013] HTTP Req                                      URL="https://[REDACTED].duosecurity.com/frame/status/[REDACTED]" http=client method=POST
> DEBU[0013] HTTP Res                                      Status="200 OK" http=client
> DEBU[0013] HTTP Req                                      URL="https://console.jumpcloud.com/userconsole/auth/duo" http=client method=POST
> DEBU[0013] HTTP Res                                      Status="403 Forbidden" http=client
> Response did not contain a valid SAML assertion
> Please check your username and password is correct
> To see the output follow the instructions in https://github.com/versent/saml2aws#debugging-issues-with-idps
> ```

JumpCloud refactored their submission form today (or tonight). Now they take json payload and check CSRF token, before they didn't. Please try the latest version, I pushed the changes.

**Comment by ahrenstein** [comment]
I'll give it a shot later tonight. Thanks for the fast fix!

**Comment by ahrenstein** [comment]
I'm getting a few build errors that might be macOS related
```±[A1B1⚡︎●●][master] $ make install
go install ./cmd/saml2aws
# github.com/keybase/go-keychain
cgo-gcc-prolog:203:11: warning: 'SecTrustedApplicationCreateFromPath' is deprecated: first deprecated in macOS 10.15 - No longer supported [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrustedApplication.h:59:10: note: 'SecTrustedApplicationCreateFromPath' has been explicitly marked deprecated here
# github.com/versent/saml2aws/v2/pkg/provider/jumpcloud
pkg/provider/jumpcloud/jumpcloud.go:187:1: syntax error: unexpected <<, expecting }
pkg/provider/jumpcloud/jumpcloud.go:202:1: syntax error: unexpected ==, expecting }
pkg/provider/jumpcloud/jumpcloud.go:207:3: syntax error: non-declaration statement outside function body
pkg/provider/jumpcloud/jumpcloud.go:218:60: method has multiple receivers
pkg/provider/jumpcloud/jumpcloud.go:218:60: syntax error: unexpected {, expecting name or (
make: *** [install] Error 2```

**Comment by logingood** [comment]
> I'm getting a few build errors that might be macOS related
> 
> ```
> go install ./cmd/saml2aws
> # github.com/keybase/go-keychain
> cgo-gcc-prolog:203:11: warning: 'SecTrustedApplicationCreateFromPath' is deprecated: first deprecated in macOS 10.15 - No longer supported [-Wdeprecated-declarations]
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrustedApplication.h:59:10: note: 'SecTrustedApplicationCreateFromPath' has been explicitly marked deprecated here
> # github.com/versent/saml2aws/v2/pkg/provider/jumpcloud
> pkg/provider/jumpcloud/jumpcloud.go:187:1: syntax error: unexpected <<, expecting }
> pkg/provider/jumpcloud/jumpcloud.go:202:1: syntax error: unexpected ==, expecting }
> pkg/provider/jumpcloud/jumpcloud.go:207:3: syntax error: non-declaration statement outside function body
> pkg/provider/jumpcloud/jumpcloud.go:218:60: method has multiple receivers
> pkg/provider/jumpcloud/jumpcloud.go:218:60: syntax error: unexpected {, expecting name or (
> make: *** [install] Error 2```
> ```

It is safe to ignore the warning above, however the syntax errors are strange. I think you might started to rebase/merge (symbols like `>>` are from merge diff) and didn't work out the diff. I have rebased the code against master recently. You should do `git pull --rebase` or smth like that, then build. Or just re-clone my fork.

**Comment by ahrenstein** [comment]
Thanks! It's working great now! I hope this is able to be merged.

**Comment by logingood** [comment]
thanks a lot for merging this!

**Pull request merged**
