### PR TITLE
Add global mfa-token flag

### PR DESCRIPTION
**Pull request by Rukenshia**
This flag allows easier automation for running saml2aws with
--skip-prompt. Only Keycloak and ADFS are currently supported.

---
In my exact use case, [saml2aws-auto](https://github.com/Rukenshia/saml2aws-auto), I currently have to rely on passing the MFA token by sending it through `stdin`. This does, however, not work reliably on Windows. I think this addition is quite useful for `--skip-prompt` use cases.

### CODE REVIEW

**Comment by Rukenshia** [comment]
This PR will probably only work if you switch all imports to my fork. I had to do that while developing but obviously switched it back for the PR.

**Comment by Rukenshia** [comment]
Yup, you're right. My bad. just pushed a commit that should fix the test.

**Comment by Rukenshia** [comment]
@wolfeidau do you think this PR is acceptable in this state?

**Comment by wolfeidau** [comment]
@Rukenshia I have it cloned and wanted to try it, been traveling so haven't had a chance to road test!

In my case I need to spin up Keycloak and reconfigure to do it, hence the delay.

**Comment by Rukenshia** [comment]
Sure, no problem. Thank you!

**Pull request merged**
