### PR TITLE
Get the AWS destination from the Destination, not Audience

### PR DESCRIPTION
**Pull request by duckfez**
Additional work on top of #469 to support how Okta's SAML response is formatted.  Okta returns the `Audience` as `urn:amazon:webservices` which is not that useful.   So this updates to grab the `Destination` attribute of the root element of the SAML response.

### CODE REVIEW

**Comment by missingcharacter** [comment]
Thanks @duckfez

**Comment by duckfez** [comment]
@missingcharacter I think this is the last one.  This fixes the blank `region=` that was showing up in my credentials file.

**Comment by missingcharacter** [comment]
@duckfez I can confirm this works for me too, thanks :)

**Comment by missingcharacter** [comment]
I closed https://github.com/Versent/saml2aws/pull/469 in favor or this PR

**Comment by missingcharacter** [comment]
I just tested these new changes and still works, once again, thanks @duckfez

**Comment by missingcharacter** [comment]
Thanks @wolfeidau

**Pull request merged**
