### PR TITLE
Revert "Merge pull request #1022 from gliptak/coverage9"

### PR DESCRIPTION
**Pull request by gliptak**
This reverts commit ee52276abb758dda7b7f50b82b81857c26f4d480, reversing changes made to bea61fbd073c111a040eff2417f1601e1c6b8a43.

### CODE REVIEW

**Comment by gliptak** [comment]
@mcampbellsb please check executable published at https://github.com/Versent/saml2aws/actions/runs/4931131122?pr=1046

if succeeds, let's plan to merge this

**Review by mapkon — COMMENTED** [review]
Does this fix https://github.com/Versent/saml2aws/issues/1041?

**Comment by gliptak** [comment]
@mapkon I'm looking to @mcampbellsb (and others to validate)

**Comment by doryphores** [comment]
For what it's worth, I just tried the darwin arm64 version from https://github.com/Versent/saml2aws/actions/runs/4931131122?pr=1046 and I no longer get the error so it looks like a good fix.

**Comment by mcampbellsb** [comment]
> @mcampbellsb please check executable published at https://github.com/Versent/saml2aws/actions/runs/4931131122?pr=1046
> 
> if succeeds, let's plan to merge this

@gliptak   https://github.com/Versent/saml2aws/pull/1046#issuecomment-1542518302

**Comment by mapkon** [comment]
OK - I will merge and prepare a release for tomorrow or saturday. @gliptak Can you approve this?

**Comment by gliptak** [comment]
@mapkon yes, please this revert PR

**Pull request merged**
