### PR TITLE
feat: add pingntlm provider support for pre-authentication issue

### LINKED ISSUE #244: support of pre-authentication (basic,ntlm,ff)
If the website to the IdP requires authentication, saml2aws fails with error 401.

```
User-Agent: saml2aws/1.0 (linux amd64) Versent
Accept-Encoding: gzip


request for url: https://pingserver/idp/startSSO.ping?PartnerSpId=urn:amazon:awsntlmprotected failed status: 401 Unauthorized

```

### PR DESCRIPTION
**Pull request by Gearheads**
This PR will add support for the `pingntlm` provider which is needed for pre-authentication issues.

Fixes #244 

Thank you to @richardcase for the solution, and help.

I didn't see a `CONTRIBUTING.md`, so please let me know if there is anything that needs to be changed.
`make mod` and `make test` both completed successfully.

### CODE REVIEW

**Comment by Gearheads** [comment]
hi @wolfeidau, I am new here, so apologies in advance if I am mistaken, but would you or someone else be able to review this?

**Comment by Gearheads** [comment]
hi @wolfeidau, apologies to bother you, just checking in if you or someone else be able to review this?

**Comment by wolfeidau** [comment]
@Gearheads hey is there a reason this needs to be a new provider entirely? 

I would love some background on the configuration and setup for Ping.

**Comment by Gearheads** [comment]
> @Gearheads hey is there a reason this needs to be a new provider entirely?
> 
> I would love some background on the configuration and setup for Ping.

hi @wolfeidau, apologies, unfortunately I do not have the full context for this change. 😞 

@richardcase, would you be able to provide more background?

**Comment by Gearheads** [comment]
Hi @wolfeidau, apologies to bother, do you think this PR will be helpful, or do you think there is a better solution to support this type of provider?

**Comment by mapkon** [comment]
@Gearheads This is failing the build. Can you take a look?

**Comment by Gearheads** [comment]
Yes, I will take look.

**Comment by Gearheads** [comment]
Hi @mapkon, I have updated the PR with more unit tests. Is there a way for me to re-run the `Codecov Report`?

**Comment by mapkon** [comment]
> Hi @mapkon, I have updated the PR with more unit tests. Is there a way for me to re-run the `Codecov Report`?

Done! I will review this today

**Review by mapkon — CHANGES_REQUESTED** [review]
@Gearheads Can you please take a look at the lint issues.

**Comment by Gearheads** [comment]
> @Gearheads Can you please take a look at the lint issues.

Hi @mapkon, yes of course. I have ran the lint command locally, and it should be fixed now.

**Comment by mapkon** [comment]
@Gearheads Looks like the tests are still complaining

**Comment by Gearheads** [comment]
> @Gearheads Looks like the tests are still complaining

Hi @mapkon, strange. It appears that the issue is with a different provide:
```
=== RUN   TestVerifyEndpointHealth
    okta_test.go:821: 
        	Error Trace:	/Users/runner/work/saml2aws/saml2aws/pkg/provider/okta/okta_test.go:821
        	            				/Users/runner/work/saml2aws/saml2aws/pkg/provider/okta/okta_test.go:728
        	            				/Users/runner/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2938
        	            				/Users/runner/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2009
        	            				/Users/runner/hostedtoolcache/go/1.21.5/x64/src/runtime/asm_amd64.s:1650
        	Error:      	Not equal: 
        	            	expected: "/report"
        	            	actual  : "/frame/check_endpoint_app_status"
```
I tried running `make test` locally, and I did not get the same error message:
```
make test
--- test all the things
?       github.com/versent/saml2aws/v2/cmd/saml2aws     [no test files]
ok      github.com/versent/saml2aws/v2  (cached)        coverage: 48.6% of statements
?       github.com/versent/saml2aws/v2/helper/credentials       [no test files]
?       github.com/versent/saml2aws/v2/mocks    [no test files]
?       github.com/versent/saml2aws/v2/pkg/creds        [no test files]
?       github.com/versent/saml2aws/v2/pkg/dump [no test files]
ok      github.com/versent/saml2aws/v2/cmd/saml2aws/commands    (cached)        coverage: 14.7% of statements
ok      github.com/versent/saml2aws/v2/helper/osxkeychain       (cached)        coverage: 75.4% of statements
ok      github.com/versent/saml2aws/v2/pkg/awsconfig    (cached)        coverage: 43.0% of statements
ok      github.com/versent/saml2aws/v2/pkg/cfg  (cached)        coverage: 60.9% of statements
ok      github.com/versent/saml2aws/v2/pkg/cookiejar    (cached)        coverage: 93.8% of statements
ok      github.com/versent/saml2aws/v2/pkg/flags        (cached)        coverage: 66.7% of statements
ok      github.com/versent/saml2aws/v2/pkg/page (cached)        coverage: 50.0% of statements
ok      github.com/versent/saml2aws/v2/pkg/prompter     (cached)        coverage: 36.5% of statements
?       github.com/versent/saml2aws/v2/pkg/provider/adfs        [no test files]
?       github.com/versent/saml2aws/v2/pkg/provider/akamai      [no test files]
ok      github.com/versent/saml2aws/v2/pkg/provider     (cached)        coverage: 49.3% of statements
ok      github.com/versent/saml2aws/v2/pkg/provider/aad (cached)        coverage: 77.1% of statements
ok      github.com/versent/saml2aws/v2/pkg/provider/adfs2       (cached)        coverage: 56.2% of statements
ok      github.com/versent/saml2aws/v2/pkg/provider/auth0       (cached)        coverage: 68.7% of statements
ok      github.com/versent/saml2aws/v2/pkg/provider/authentik   (cached)        coverage: 77.8% of statements
ok      github.com/versent/saml2aws/v2/pkg/provider/browser     (cached)        coverage: 58.8% of statements
ok      github.com/versent/saml2aws/v2/pkg/provider/f5apm       (cached)        coverage: 42.5% of statements
ok      github.com/versent/saml2aws/v2/pkg/provider/googleapps  (cached)        coverage: 34.3% of statements
ok      github.com/versent/saml2aws/v2/pkg/provider/jumpcloud   (cached)        coverage: 17.7% of statements
ok      github.com/versent/saml2aws/v2/pkg/provider/keycloak    (cached)        coverage: 47.7% of statements
?       github.com/versent/saml2aws/v2/pkg/provider/onelogin/mock       [no test files]
ok      github.com/versent/saml2aws/v2/pkg/provider/netiq       (cached)        coverage: 49.0% of statements
ok      github.com/versent/saml2aws/v2/pkg/provider/okta        (cached)        coverage: 45.7% of statements
ok      github.com/versent/saml2aws/v2/pkg/provider/onelogin    (cached)        coverage: 54.4% of statements
ok      github.com/versent/saml2aws/v2/pkg/provider/pingfed     (cached)        coverage: 39.9% of statements
ok      github.com/versent/saml2aws/v2/pkg/provider/pingntlm    (cached)        coverage: 60.3% of statements
?       github.com/versent/saml2aws/v2/pkg/provider/shell       [no test files]
?       github.com/versent/saml2aws/v2/pkg/provider/shibboleth  [no test files]
ok      github.com/versent/saml2aws/v2/pkg/provider/pingone     (cached)        coverage: 10.2% of statements
ok      github.com/versent/saml2aws/v2/pkg/provider/shibbolethecp       (cached)        coverage: 38.6% of statements
ok      github.com/versent/saml2aws/v2/pkg/samlcache    (cached)        coverage: 67.1% of statements
ok      github.com/versent/saml2aws/v2/pkg/shell        (cached)        coverage: 100.0% of statements
```
I am wondering if maybe the order of these handlers is important?
https://github.com/Versent/saml2aws/blob/master/pkg/provider/okta/okta_test.go#L812

Any ideas as to what I can check out, or if it is worth re-running the GitHub action to see if it was a one-time issue?

**Comment by mapkon** [comment]
@Gearheads I re-ran the github actions and got a similar result to the the one above.

**Comment by mapkon** [comment]
> @Gearheads I re-ran the github actions and got a similar result to the the one above.

I just re-ran it and it passed. Something weird is going on.

**Review by mapkon — APPROVED** [review]

**Pull request merged**
