### PR TITLE
Correct Appveyor/Chocolatey build

### PR DESCRIPTION
**Pull request by gliptak**
https://github.com/golang/dep/issues/2086#issuecomment-456263598

### CODE REVIEW

**Comment by gliptak** [comment]
@wolfeidau not sure how Appveyor builds are triggered ...

https://github.com/Versent/saml2aws/issues/426

**Comment by wolfeidau** [comment]
I spent a bit of time debugging this build on a branch, I haven't been able to test building this project on windows as I don't have a machine setup for builds.

Have you built the current master branch on windows?

As in:
1. Clone the repo.
2. Install golang for windows.
3. Run `go build -o saml2aws ./cmd/saml2aws`  in the cloned repo.

**Comment by gliptak** [comment]
https://github.com/gliptak/saml2aws/pull/1/checks?check_run_id=451592626 (I'm not sure why the step is green)

```
# github.com/karalabe/hid
In file included from C:\Users\runneradmin\go\pkg\mod\github.com\karalabe\hid@v1.0.0\hid_enabled.go:40:
C:\Users\runneradmin\go\pkg\mod\github.com\karalabe\hid@v1.0.0/hidapi/windows/hid.c: In function 'hid_enumerate':
##[error]C:\Users\runneradmin\go\pkg\mod\github.com\karalabe\hid@v1.0.0/hidapi/windows/hid.c:431:5: warning: 'strncpy' specified bound depends on the length of the source argument [-Wstringop-overflow=]
     strncpy(cur_dev->path, str, len+1);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[error]C:\Users\runneradmin\go\pkg\mod\github.com\karalabe\hid@v1.0.0/hidapi/windows/hid.c:429:11: note: length computed here
     len = strlen(str);
           ^~~~~~~~~~~
```

There is an open issue at https://github.com/karalabe/hid/issues/23

**Comment by wolfeidau** [comment]
@gliptak The issue is that appveyor uses a powershell wrapper script for that step, if that script detects ANY output on stderr from a program, such as compiler warnings.. It will bomb out.

We need to redirect the stderr output from go build using the example in the below post.

https://help.appveyor.com/discussions/problems/10014-false-build-fail-status

**Comment by gliptak** [comment]
@wolfeidau the build link above point to Github Actions and it has the opposite issue. The build steps fails, while the job is marked green.

**Comment by gliptak** [comment]
@wolfeidau would you be open to cut a minor release (including this PR) to see if Appveyor build gets corrected?

https://chocolatey.org/packages/saml2aws#versionhistory

**Pull request closed without merging**
