### PR TITLE
Add Linux install instructions

### PR DESCRIPTION
**Pull request by brombomb**

### CODE REVIEW

**Comment by wolfeidau** [comment]
I totally need to add a section for this, so thanks!

Did you consider downloading the `saml2aws_2.10.0_linux_amd64.tar.gz` file using curl and copying it to `~/bin`? 

```
#!/bin/bash
VERSION=2.10.0
curl -L -O https://github.com/Versent/saml2aws/releases/download/v${VERSION}/saml2aws_${VERSION}_darwin_amd64.tar.gz
tar xvzf saml2aws_${VERSION}_darwin_amd64.tar.gz --directory ~/bin
```

This is similar to what the homebrew recipe does.

**Comment by brombomb** [comment]
It took me quite a while to build using go, since I've never used it before.  Then once I found that my version didn't match my coworkers, I found the tar.gz and moved it to `/usr/local/bin`

**Comment by nshenry03** [comment]
Hey @brombomb / @wolfeidau any progress on getting this merged?  This is what I used to install on linux.. LMK if you want me to submit a PR, I just didn't want to step on any toes.

```bash
VERSION='2.13.0'
BIN_DIR="${HOME}/.local/bin"

TAR="saml2aws_${VERSION}_linux_amd64.tar.gz"
SHA="saml2aws_${VERSION}_linux_amd64.sha512"

URL="https://github.com/Versent/saml2aws/releases/download/v${VERSION}"

curl --location --remote-name --silent \
  ${URL}/${TAR}

curl --location --remote-name --silent \
  ${URL}/${SHA}

if sha512sum -c ${SHA}
then
  tar -xf ${TAR} --directory ${BIN_DIR}

  rm -f ${TAR}
  rm -f ${SHA}
fi
```

Thanks!

**Comment by marshallpierce** [comment]
I'm new to golang so maybe there's something "obvious" I'm missing, but here's what I'm doing:

```
$ git status
HEAD detached at v2.14.0
nothing to commit, working tree clean
```

with empty `$GOPATH/{bin,pkg}`:

```
$ make && make install
...
$ saml2aws --version
1.0.0
```

Why does it say 1.0.0?

**Comment by gliptak** [comment]
README was already updates with Linux section https://github.com/Versent/saml2aws#linux

**Review by mapkon — APPROVED** [review]

**Comment by mapkon** [comment]
> README was already updates with Linux section https://github.com/Versent/saml2aws#linux

I think this is referring to installing the dev version via `make`. The link documents the installation via `wget`.

@brombomb Could you be kind enough to update from master (to resolve conflicts)?

**Comment by brombomb** [comment]
Opened #981 since this branch no longer exists I was unable to update it from here.

**Pull request closed without merging**
