### PR TITLE
1128 - Print the entropy to stderr regardless of quiet mode

### PR DESCRIPTION
**Pull request by eacherkan-aternity**
Judging by the `prompter.StringRequired("Enter verification code")` usage in the same method, I assume that it's reasonable to print to `stderr` if user input is required, even in quiet mode.

The logger's destination is set in `main.go`, either to `io.Discard` (in quiet mode), or to `os.Stderr` otherwise. Since at the moment there's no great flexibility in the logger configuration, I propose a simple solution by printing the specific line `Phone approval required. Entropy is: %d` always to `stderr`. I implement this by saving the previous destination aside, and putting it back after the `Printf`.

Potential downsides of this solution include:
- If at some point complex logger configuration is required, this will be one more place to fix.
- The UX is different from interactions that require user input, which go through the `prompter`. However, the `prompter` framework doesn't seem to have facilities for an informative user message that doesn't require input.

### CODE REVIEW

**Review by mapkon — CHANGES_REQUESTED** [review]
Hey @eacherkan-aternity 

Our code coverage has gone down. Can you write a test that exercises the `else` branch?

**Comment by eacherkan-aternity** [comment]
Hi @mapkon, I [added a unit test](https://github.com/Versent/saml2aws/pull/1129/commits/6dda3cea08660b153d6c0f8338ae1c9af473a22b) per your request.

**Comment by eacherkan-aternity** [comment]
I took the liberty of merging the recent changes from master to the branch. Looking at last night's build failure, I don't understand why it failed - the only failed tests seem to come from `okta_test`, unrelated to this branch's changes. All tests pass successfully on my machine.

**Comment by mapkon** [comment]
> I took the liberty of merging the recent changes from master to the branch. Looking at last night's build failure, I don't understand why it failed - the only failed tests seem to come from `okta_test`, unrelated to this branch's changes. All tests pass successfully on my machine.

I sometimes get these intermittent failures -

**Comment by eacherkan-aternity** [comment]
@mapkon What are the next steps? Is anything required from my side?

**Comment by mapkon** [comment]
CC: @wolfeidau @gliptak

**Comment by gliptak** [comment]
thank your for the detailed analysis @eacherkan-aternity 

while survey doesn't seem to have native support for stderr/always display, consider moving the stderr switching functionality into prompter

PS #1147

**Comment by mapkon** [comment]
> thank your for the detailed analysis @eacherkan-aternity
> 
> while survey doesn't seem to have native support for stderr/always display, consider moving the stderr switching functionality into prompter
> 
> PS #1147

@eacherkan-aternity Any response to this?

**Comment by eacherkan-aternity** [comment]
@mapkon I think the decision whether the currently proposed solution is reasonable or whether the functionality should go into prompter should be yours (the maintainers'). As a first-time contributor I don't feel familiar enough with the project to make a design decision.

If you reject the current proposal (which of course is absolutely fine, no hard feelings whatsoever), I can try to move the functionality into prompter. As far as I understand, this entails:
1. Adding a new function for output-only (called `Print`? `Display`?) to the `Prompter` interface,
2. Implementing it in `CliPrompter` and `PinentryPrompter`,
3. Replacing some of the calls to `log.Print*` across the codebase with the new function,
4. Adding unit tests.

Does that make sense?

**Comment by gliptak** [comment]
thank you for detailing approach above. is there a need for separate PinentryPrompter or would CliPrompter gain additional methods? consider formulating above as a separate PR (and we could rebase this PR on it)

**Comment by mapkon** [comment]
> @mapkon I think the decision whether the currently proposed solution is reasonable or whether the functionality should go into prompter should be yours (the maintainers'). As a first-time contributor I don't feel familiar enough with the project to make a design decision.
> 
> If you reject the current proposal (which of course is absolutely fine, no hard feelings whatsoever), I can try to move the functionality into prompter. As far as I understand, this entails:
> 
> 1. Adding a new function for output-only (called `Print`? `Display`?) to the `Prompter` interface,
> 2. Implementing it in `CliPrompter` and `PinentryPrompter`,
> 3. Replacing some of the calls to `log.Print*` across the codebase with the new function,
> 4. Adding unit tests.
> 
> Does that make sense?

Thanks mate for the submission, and I appreciate your work on this, and contribution to open source.

To be fair, I maintain the project mainly by testing dependency updates and merging PRs. For the heavy lifting stuff, I defer to @gliptak and @wolfeidau for guidance, since they have more context than I do.

I would take their word over mine.

**Comment by mapkon** [comment]
> @mapkon I think the decision whether the currently proposed solution is reasonable or whether the functionality should go into prompter should be yours (the maintainers'). As a first-time contributor I don't feel familiar enough with the project to make a design decision.
> 
> If you reject the current proposal (which of course is absolutely fine, no hard feelings whatsoever), I can try to move the functionality into prompter. As far as I understand, this entails:
> 
> 1. Adding a new function for output-only (called `Print`? `Display`?) to the `Prompter` interface,
> 2. Implementing it in `CliPrompter` and `PinentryPrompter`,
> 3. Replacing some of the calls to `log.Print*` across the codebase with the new function,
> 4. Adding unit tests.
> 
> Does that make sense?

@eacherkan-aternity Any update on this?

**Comment by eacherkan-aternity** [comment]
@mapkon I'm working on the implementation.

> is there a need for separate PinentryPrompter or would CliPrompter gain additional methods?
I don't see a need for a separate prompter, I would add a method to `CliPrompter`.

**Comment by mapkon** [comment]
> @mapkon I'm working on the implementation.
> 
> > is there a need for separate PinentryPrompter or would CliPrompter gain additional methods?
> 
> I don't see a need for a separate prompter, I would add a method to `CliPrompter`.

If that is easier to implement, lets go for that

**Comment by eacherkan-aternity** [comment]
Hi,
I implemented the change in `Prompter` and adjusted the tests accordingly.

**Review by gliptak — APPROVED** [review]
:+1:

**Review by mapkon — CHANGES_REQUESTED** [review]
The linter is failing. Please take a look

**Comment by eacherkan-aternity** [comment]
Sorry. Fixed by running `gofmt` and `goimports`. Verified that `golangci-lint` runs without errors on my machine.

**Review by mapkon — APPROVED** [review]

**Pull request merged**
