### PR TITLE
Initial Dockerfile

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Review by mapkon — COMMENTED** [review]
I am not sure I see the benefit of this - however, if this was coupled with a list of instructions on how to run/test, that would be awesome. Actually, we need a test harness of thoughts -- or rather a list of things to check before we release - 

Can we at least look into that?

**Comment by gliptak** [comment]
@mapkon you build/run this like other Docker packaged utilities

```
docker build --tag saml2aws:latest .
...
docker run -saml2aws:latest
usage: saml2aws [<flags>] <command> [<args> ...]

A command line tool to help with SAML access to the AWS token service.
...
```

I'm offering this as starting point packaging `libudev` dependency

for actual use, we would likely mount config folder (and more)

maybe @BenPhegan have pointers on target (CI/desktop) usage

**Comment by mapkon** [comment]
> @mapkon you build/run this like other Docker packaged utilities
> 
> ```
> docker build --tag saml2aws:latest .
> ...
> docker run -saml2aws:latest
> usage: saml2aws [<flags>] <command> [<args> ...]
> 
> A command line tool to help with SAML access to the AWS token service.
> ...
> ```
> 
> I'm offering this as starting point packaging `libudev` dependency
> 
> for actual use, we would likely mount config folder (and more)
> 
> maybe @BenPhegan have pointers on target (CI/desktop) usage

@gliptak I know how to use docker, but thanks for explaining. My question was why this was added especially since it does not have an actual use case as of now (like you mentioned, we would need to mount a config folder or similar).

Anyhow, let's see how this evolves.

**Comment by BenPhegan** [comment]
@gliptak - Thanks for the Docker example.  Will take it as a base for implementing an Alpine version.

@mapkon / @gliptak - As for usage, we are using a Docker image that I built based of a previous version to enable anyone in our organisation to authenticate to AWS very simply regardless of their OS or existing installed applications.  It is a single command built into a Makefile in each repository, with the expectation that the only requirements to build the software is a version of `make` and Docker installed.  This also ensures separation of authentication per repository, as we place the authentication root and all `.aws` directory related auth data within the repository directory.

An example command line we use is similar to this (albeit inside the Makefile so the variables are different):

```bash
docker run --user $(id -u):$(id -g) -it --rm -v $PWD:delegated -w $PWD-e SAML2AWS_USERNAME -e AWS_CONFIG_FILE=$PWD/.aws/config -e AWS_SHARED_CREDENTIALS_FILE=$PWD/.aws/credentials "benphegan/saml2aws:latest" --role=arn:aws:iam::$ACCOUNT:role/$ROLE --mfa=Auto --idp-provider=GoogleApps --url="https://accounts.google.com/o/saml2/initsso?idpid=$IDPID&spid=$SPID&forceauthn=false" login --credentials-file=$PWD/.aws/credentials --profile=sts --cache-saml --cache-file=$PWD/.aws/saml2aws/cache_default
```

You could do the same for CI/CD, however we actually choose an OIDC provider where available instead. 

I can look into what a basic sanity test of the image would look like.  If we run the tests within the container, that ensures that MUSL vs glibc works fine for at least tested codepaths (assumption is that this will Just Work<sup>(TM)</sup>).  And a non-zero exit condition on running the resultant deployment image would provide some sanity around Docker image packaging.  Will look into those as a start.

Let me know if you want any further information on usage?

**Comment by mapkon** [comment]
> @gliptak - Thanks for the Docker example. Will take it as a base for implementing an Alpine version.
> 
> @mapkon / @gliptak - As for usage, we are using a Docker image that I built based of a previous version to enable anyone in our organisation to authenticate to AWS very simply regardless of their OS or existing installed applications. It is a single command built into a Makefile in each repository, with the expectation that the only requirements to build the software is a version of `make` and Docker installed. This also ensures separation of authentication per repository, as we place the authentication root and all `.aws` directory related auth data within the repository directory.
> 
> An example command line we use is similar to this (albeit inside the Makefile so the variables are different):
> 
> ```shell
> docker run --user $(id -u):$(id -g) -it --rm -v $PWD:delegated -w $PWD-e SAML2AWS_USERNAME -e AWS_CONFIG_FILE=$PWD/.aws/config -e AWS_SHARED_CREDENTIALS_FILE=$PWD/.aws/credentials "benphegan/saml2aws:latest" --role=arn:aws:iam::$ACCOUNT:role/$ROLE --mfa=Auto --idp-provider=GoogleApps --url="https://accounts.google.com/o/saml2/initsso?idpid=$IDPID&spid=$SPID&forceauthn=false" login --credentials-file=$PWD/.aws/credentials --profile=sts --cache-saml --cache-file=$PWD/.aws/saml2aws/cache_default
> ```
> 
> You could do the same for CI/CD, however we actually choose an OIDC provider where available instead.
> 
> I can look into what a basic sanity test of the image would look like. If we run the tests within the container, that ensures that MUSL vs glibc works fine for at least tested codepaths (assumption is that this will Just Work(TM)). And a non-zero exit condition on running the resultant deployment image would provide some sanity around Docker image packaging. Will look into those as a start.
> 
> Let me know if you want any further information on usage?

Thanks @BenPhegan 

I am not sure if the "tests" for the image are necessary. I was more thinking along the lines of defining a suite of tests we can run before we mark a given release as ready. This can be done via a docker image or documentation or similar. It should not really hold you up with your task of containerising the app.

**Review by mapkon — APPROVED** [review]

**Comment by smlx** [comment]
Because this Dockerfile doesn't use `goreleaser`, it breaks the `--version` command. It will output `1.0.0` instead of the real version.

**Comment by mapkon** [comment]
Do you guys want to merge this to master? What is the plan for this @gliptak / @BenPhegan ?

**Comment by BenPhegan** [comment]
@mapkon - I will put some time aside today to try and get this and the other PR aligned.

**Comment by BenPhegan** [comment]
For clarity, I looked at using this Dockerfile as part of https://github.com/Versent/saml2aws/pull/890 however it cannot easily be used with `goreleaser`.  I have used a different approach with a static binary. This approach copies over the libudev dependency.  I would suggest either closing this one and addressing any issue with the other PR, or moving some of the goreleaser changes to this one.  @gliptak - your thoughts?

**Comment by mapkon** [comment]
> For clarity, I looked at using this Dockerfile as part of #890 however it cannot easily be used with `goreleaser`. I have used a different approach with a static binary. This approach copies over the libudev dependency. I would suggest either closing this one and addressing any issue with the other PR, or moving some of the goreleaser changes to this one. @gliptak - your thoughts?

I will close this, and focus our efforts on #890. Is that ready to be merged?

**Comment by mapkon** [comment]
Closing as it duplicates #890 efforts

**Pull request closed without merging**
