### PR TITLE
Support multiple fido devices in Okta

### PR DESCRIPTION
**Pull request by dustinblackman**
## Overview

Okta allows you to attach multiple Fido devices to your account, but `saml2aws` will only attempt the use the first device in the list returned from Okta. This results in an authentication failure if the local device does not match, with no way to select another device. This PR iterates through each Fido device on the account looking for a match on the local system. 

This required a slight refactor to make requests to Okta's verification endpoints more reusable, but will make future refactoring easier.

### CODE REVIEW

**Comment by jayzalowitz** [comment]
+1 for this

**Comment by cdchris12** [comment]
Huge +1 for this; we can't use multiple factors through Okta via saml2aws without this functionality

**Comment by amazee-jp** [comment]
Yes, +1 please!

**Comment by dustinblackman** [comment]
Anything I can do to get this merged?

**Comment by wolfeidau** [comment]
I have moved the code to #630 and will merge it now 🎉 thanks a lot @dustinblackman

**Pull request closed without merging**
