### PR TITLE
Update the googleapps IDP provider to work with changes to Google log…

### PR DESCRIPTION
**Pull request by aaronthebaron**
…in page while maintaining gaialogin compatibility

Attempting to fix the issues with the GoogleApps IdP provider noted in the issue #1259 

The google login system has changed for most but not all users causing this provider to no longer work for a majority of our in house users.

I have tested this with the new pages, in a configuration requiring 2-factor authentication with a phone app. I have not been able to regression test this with the current login, but I have tried to keep that legacy flow intact with my changes. I have also not been able to test each challenge but I have modified the challenges in a way that I hope to be backwards compatible.

### CODE REVIEW

**Comment by edwardrf** [comment]
Awesome PR, but it seems I am still unable to login with the following error:
```
Using IdP Account default to access GoogleApps https://accounts.google.com/o/saml2/initsso?idpid=C00mmafdv&spid=XXXXXXXXXXXX&forceauthn=false
Authenticating as XXX@XXXXXX.XXX ...
Error authenticating to IdP.: error loading challenge page: unable to extract skip form: could not find form with query "form[action$=\"skip\"]"
```

**Review by mapkon — COMMENTED** [review]
@aaronthebaron is this ready for review?

Also, lots of changes here - do you reckon we should cover some of the missing lines with tests?

**Comment by edwardrf** [comment]
@aaronthebaron 
Please see the log in the attachment
[test.log](https://github.com/user-attachments/files/15603282/test.log)

**Comment by aaronthebaron** [comment]
@mapkon 

> @aaronthebaron is this ready for review?
> 
> Also, lots of changes here - do you reckon we should cover some of the missing lines with tests?

Yes, this is ready for review.

Of all the lines I've added, most of them are under existing testing. I've added a test and modified another test to cover the two main changes.

There are so many paths possible in this provider that I don't have access to, but current this is passing regression.

More paths will be breaking that I won't be able to fix and should probably be handed in another pull reqest.

**Comment by aaronthebaron** [comment]
@edwardrf Thank you for providing the output. Unfortunately you are entering a part of the flow that handles multiple challenge possibilities (TOTP, U2F, etc) and that page has completely changed.

Originally it must've been a form with multiple actions but now looks to be divs with different annotations. I think a lot more work will need to happen to get this page working again and I'm not sure I can spend more time on it.

The code for that page can be found [here](https://github.com/Versent/saml2aws/blob/master/pkg/provider/googleapps/googleapps.go#L497).

A quick fix for you personally might be to remove some possible authentication methods. Sorry I can't do more at this time.

**Review by mapkon — APPROVED** [review]

**Pull request merged**
