### PR TITLE
Move playwright-go from mxschmitt to playwright-community

### PR DESCRIPTION
**Pull request by gliptak**
#952 

I didn't test browser path of resulting binary

### CODE REVIEW

**Comment by mapkon** [comment]
> #952
> 
> I didn't test browser path of resulting binary

Thanks @gliptak - how would we verify that?

**Comment by gliptak** [comment]
while there might be coverage in tests, considering the large space of environments, maybe issue submitters could be requested to test PR builds?

#984 
https://github.com/Versent/saml2aws/actions/runs/4398152074
https://github.com/Versent/saml2aws/suites/11507705184/artifacts/594845640

**Comment by mapkon** [comment]
> https://github.com/Versent/saml2aws/suites/11507705184/artifacts/594845640

That is a good point. Alternatively, the author can also list the environments where they need help testing. That way, we can rally efforts around verifying the change. 

A case could be made that it might not be necessarily for a library change like this one, but without a test suite to exercise the execution paths, it is really guessing if everything is right!

**Comment by gliptak** [comment]
@mikesir87 @wiegandf

please review https://github.com/Versent/saml2aws/suites/11511346046/artifacts/595103454 correcting for https://github.com/Versent/saml2aws/issues/952

**Pull request merged**
