### PR TITLE
Adds WebAuthn support for Okta using U2F

### PR DESCRIPTION
**Pull request by alsmola**
This change adds WebAuthn support for Okta using backwards compatibility with U2F. 

It relies on my fork of go-u2fhost, which I'm hoping can revert to the main repo once a PR is merged (https://github.com/marshallbrekka/go-u2fhost/pull/6)

I've tested that this works in my local setup, but haven't spent much time refactoring or writing tests. Let me know if you think that would be useful.

### CODE REVIEW

**Comment by wolfeidau** [comment]
This would be amazing, I would love a test or especially given it is a fork.

**Comment by alsmola** [comment]
@wolfeidau I added a couple tests, but the way the code is structured makes it difficult to add more without adding a bunch of interfaces. Let me know if you'd like to see additional kinds of tests.

**Comment by wolfeidau** [comment]
Looks great lets start with this.

**Comment by dhess** [comment]
Is this expected to work on macOS with a YubiKey 5 configured as the WebAuthn token? When I try it, I get this error message:

```
Authenticating as foo@bar.com ...
error loading credentials for profile: : error logging in: error authenticating to IdP: error verifying MFA: The provided key handle is not present on the device, or was created with a different application parameter.
```

If I change only the `mfa = FIDO` to `mfa = TOTP` in the `.saml2aws` configuration, leaving everything else the same, I'm able to authenticate after entering the TOTP code and all subsequent `saml2aws` commands work great.

My Okta account is configured for WebAuthn support, and on the same machine I'm able to log into the Okta web interface in my browser using the YubiKey as a 2nd factor.

**Pull request merged**
