### PR TITLE
Adds Google u2f support

### PR DESCRIPTION
**Pull request by mothershipper**
Update the u2f library to the upstream version, updates the mocks and
updates the Google provider to include u2f support. 

Addresses #238

### CODE REVIEW

**Comment by mothershipper** [comment]
ping @alsmola to check Okta for breakage -- it looks like your changes were merged upstream https://github.com/marshallbrekka/go-u2fhost/pull/6

Google u2f didn't seem to work using your fork, but passed as soon as I changed the import -- hoping it's not the case that this breaks Okta's webauthn support :/

**Comment by mothershipper** [comment]
Oh, my bad, didn't see your PR before opening this one -- I'll rebase this on top of yours later.

**Comment by alsmola** [comment]
This should be fine - I have a PR to go back to the source of go-u2fhost anwyays: https://github.com/Versent/saml2aws/pull/396

**Comment by mothershipper** [comment]
Just rebased

**Pull request merged**
