### PR TITLE
Adding support for SKOTP (security key based OTP), CAPTCHA display via iTerm (if available), specifying region, remove hardcoded SAML Audience url

### PR DESCRIPTION
**Pull request by missingcharacter**
I grabbed changes from @thecubed: 

- Region and audience: https://github.com/thecubed/saml2aws/commit/40f4cda846091dadf9a08146fa3b31be213b08f5
- Google SKOTP and CAPTCHA: https://github.com/thecubed/saml2aws/commit/9781c437f393f5b3027094592ab22553e15ae81f
- Finally, if yubikey fails it asks for SKOTP

### CODE REVIEW

**Comment by missingcharacter** [comment]
Thanks @wolfeidau

**Comment by missingcharacter** [comment]
@wolfeidau is there something wrong with this PR?

**Comment by wolfeidau** [comment]
@missingcharacter Yeah this PR does a few things so it will take me a bit longer to test and understand all the changes.

Sadly given I am busy at the moment I am more likely to merge changes which just focus on one thing.

So i typically accept changes localised to a particular provider quicker than global changes like SAML Audience url.

If you really want things merged quickly in the future I would really appreciated it if you broke things into bite size pieces.

cheers

**Comment by missingcharacter** [comment]
@wolfeidau let me try to break this into smaller chunks

**Comment by missingcharacter** [comment]
I'm breaking this PR into multiple, first PR is here: https://github.com/Versent/saml2aws/pull/469

**Comment by missingcharacter** [comment]
Second PR https://github.com/Versent/saml2aws/pull/470

**Pull request closed without merging**
