### PR TITLE
Return more informative error message incase there is no sessionToken

### LINKED ISSUE #822: Show meaningful error, when mfa response does not contain session token
Hello,

First of all, thanks for this great tool.

I would like to report an issue, which have happened to me today.  I tried to login using `saml2aws` as usually. My session would look like this:
```
saml2aws login
Using IdP Account default to access Okta <redacted>
To use saved password just hit enter.
? Username <redacted>
? Password

Authenticating as <redacted> ...
? Select which MFA option to use TOTP MFA authentication
? Enter verification code 106105
Error authenticating to IdP.: unable to create an okta session, nil input
```
After some digging and rerunning with `DUMP_CONTENT=true saml2aws login --force --verbose` it turned out that my password in Okta has expired. The response I would receive from okta is at the end of this issue.

I propose that `verifyMfa` should check if the payload actually contains session token and return error if it does not.

I would like to work on this issue. I should be able to submit a PR shortly.

```{
  "stateToken": "<redacted>",
  "expiresAt": "2022-05-16T11:05:48.000Z",
  "status": "PASSWORD_EXPIRED",
  "_embedded": {
    "user": {
      "id": "<redacted>",
      "profile": {
        "login": "<redacted>",
        "firstName": "Krysztof",
        "lastName": "Drys",
        "locale": "en_US",
        "timeZone": "America/Los_Angeles"
      }
    },
    "policy": {
      "complexity": {
        "minLength": 8,
        "minLowerCase": 1,
        "minUpperCase": 1,
        "minNumber": 1,
        "minSymbol": 0,
        "excludeUsername": true
      },
      "age": {
        "minAgeMinutes": 0,
        "historyCount": 0
      }
    }
  },
  "_links": {
    "next": {
      "name": "changePassword",
      "href": "<redacted>",
      "hints": {
        "allow": [
          "POST"
        ]
      }
    },
    "cancel": {
      "href": "<redacted>",
      "hints": {
        "allow": [
          "POST"
        ]
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by krzysztofdrys**
When verifyMfa receives no session token from the remote token, it
should fail immidietly. This way saml2aws is able to use the whole
response payload to explain to the user, what went wrong. Status field
can contain meaningful information like 'PASSWORD_EXPIRED'.

Before this change, if origin returned to answer, the error returned to
the user would be: "Error authenticating to IdP.: unable to create an
okta session, nil input".

Because I have already reset my okta password, I am not sure how to actually test this code.

Closes #822

### CODE REVIEW

**Comment by mapkon** [comment]
@krzysztofdrys Merging this would reduce our code coverage. Would you hazard some tests?

**Comment by mapkon** [comment]
Nope - you can view the coverage report above! We are still down by 0.03%. I am not a stickler for coverage, but do you think you can get it to parity? We should merge if there is just no decrease.

**Review by mapkon — CHANGES_REQUESTED** [review]
After merging #1004 - this now has conflicts - could you kindly take a look?

**Comment by krzysztofdrys** [comment]
@mapkon I resolved the conflicts.

As for Codeconv report. Is there a way to refresh it?

I think it is based on my first commit. Later I added tests in [554f47c](https://github.com/Versent/saml2aws/pull/823/commits/554f47c2b7c14f8f51b6b6f4c214e1069e4a7b07) but I don't think this is included.

I am including the screenshot of the only report which I see :-) 

image

**Comment by mapkon** [comment]
> @mapkon I resolved the conflicts.
> 
> As for Codeconv report. Is there a way to refresh it?
> 
> I think it is based on my first commit. Later I added tests in [554f47c](https://github.com/Versent/saml2aws/pull/823/commits/554f47c2b7c14f8f51b6b6f4c214e1069e4a7b07) but I don't think this is included.
> 
> I am including the screenshot of the only report which I see :-)
> 
> image

Yeah, that looks strange. @gliptak - any insights?

**Comment by gliptak** [comment]
the direct link seems to be more up-to-date
https://app.codecov.io/gh/Versent/saml2aws/pull/823
although it didn't get refreshed with the line coverage details

**Review by mapkon — APPROVED** [review]
Good to go! Sorry about the codecov shenanigans

**Pull request merged**
