### PR TITLE
Add Entropy support in PhoneAppNotification for Azure Active Directory

### PR DESCRIPTION
**Pull request by marcottedan**
If the entropy field is not activated on Active Directory, the code will behave as it was. If entropy is activated, the log line will display the entropy for you to input it in the Microsoft Authenticator.

Note: Please disregard go.mod changes.

### CODE REVIEW

**Comment by dannykitchen** [comment]
Have tested this and working on windows
How can we get this to master branch ?

**Comment by tehmaspc** [comment]
Works on OSX. Thanks!

**Comment by marcottedan** [comment]
@wolfeidau The MR had my fork in the go.mod. Now it's on master, I'm not sure this is desired at all.

image

**Comment by marcottedan** [comment]
@wolfeidau I see you changed it. I think there's still 2 library that have been downgraded though: 

github.com/stretchr/testify v1.7.1
	github.com/tidwall/gjson v1.13.0

**Pull request merged**
