### PR TITLE
Support Number Challenge for Okta MFA

### PR DESCRIPTION
**Pull request by muramasa64**
Support Number Challenge for Okta MFA

https://help.okta.com/oie/en-us/Content/Topics/identity-engine/authenticators/configure-okta-verify-options.htm

### CODE REVIEW

**Comment by amasses** [comment]
@wolfeidau could we please have this (or one of the others) merged in and released? I'd really like to be able to enforce the number challenge for risk based session decisions, but until this is in place it makes it impossible to use.

**Comment by ddavison-lucid** [comment]
this repo has been pretty active since this PR was raised with other merges and enhancements. Is there some objection to this PR @wolfeidau ? Would at least help to know what that is. Quite a few looking to make use of this - ideally without maintaining a fork :)

**Review by mapkon — COMMENTED** [review]
@muramasa64 Sorry for the late response. If you can add tests, I can merge it and prepare for a release.

**Comment by silver886** [comment]
This PR looks like #1115, I added unit test for this one as well.
https://github.com/silver886/saml2aws/blob/feature/okta-number-challenge/pkg/provider/okta/okta_test.go#L197

Because I don't have Okta MFA, I'm not able to verify if the format of JSON response in the unit test is still valid.

**Comment by amasses** [comment]
@silver886 I had a quick look and the JSON content looks correct.

For reference I've captured the full payload and redacted sensitive data, and attached it - here the correctAnswer is 42. You are welcome to use some or all of this if you like.

[number-challenge-example.json.txt](https://github.com/Versent/saml2aws/files/12428492/number-challenge-example.json.txt)

**Comment by mapkon** [comment]
> @amasses Thank you for the sample data, the JSON path is the same as the unit test and there is no need to modify it. :)
> 
> @mapkon Should I open another PR or add this unit test in #1115?

  Another PR would suffice. Thank you 🙏🏿

**Comment by mapkon** [comment]
@amasses With #1115 is this still required?

**Comment by amasses** [comment]
@mapkon #1115 seems to be for Ping Identity, I don't see anything in that PR to reference Okta

**Comment by mapkon** [comment]
@amasses Got you and thanks. If you could help me fix the coverage (this PR bumps it down by 0.3%), I am happy to merge this.

**Comment by silver886** [comment]
#1116 is submitted and should increase the coverage for this PR.

**Comment by silver886** [comment]
I think we might be able to close this PR since #1116 is merged.

**Comment by muramasa64** [comment]
Sorry for leaving this pull request for so long.

@silver886 Thanks for writing the test.

This Pull Request will be closed.

**Pull request closed without merging**
