### PR TITLE
Adding AWS Region as a parameter to support multiple AWS Identity partitions

### PR DESCRIPTION
**Pull request by missingcharacter**
Breaking PR: https://github.com/Versent/saml2aws/pull/452 into multiple PRs

This one removes hardcoded Destination URLs and relies on AWS Region to determine AWS endpoints

Solves: https://github.com/Versent/saml2aws/pull/450

No tests failed

I grabbed changes from @thecubed: 

Region and audience: https://github.com/thecubed/saml2aws/commit/40f4cda846091dadf9a08146fa3b31be213b08f5

### CODE REVIEW

**Comment by wolfeidau** [comment]
@missingcharacter thanks for breaking this up, I merged one of them however this one doesn't seem to work for me when testing locally.

```
Failed to assume role, please check whether you are permitted to assume the given role for the AWS service: error parsing aws role accounts: error retrieving AWS login form: Post "urn:amazon:webservices": unsupported protocol scheme "urn"
```

I will try and take a look later as to why.

**Comment by missingcharacter** [comment]
@wolfeidau I think I fixed it now, I made a bad assumption making `us-east-1` the default value for the flag if none was specified, let me know if you run into any problems

**Comment by missingcharacter** [comment]
@wolfeidau is there something I can do to help you to merge this? are you concerned about tests?

**Comment by wolfeidau** [comment]
@missingcharacter TBH I still can't get this working for me.

```
Failed to assume role, please check whether you are permitted to assume the given role for the AWS service: error parsing aws role accounts: error retrieving AWS login form: Post "amazon-aws": unsupported protocol scheme ""
```

I tried to run this to add `Region` to my configuration.

```
saml2aws configure -a whatever-dev -r us-east-1
```

This updated my configuration and set the following attribute in that provider but still not working.
```
region               = us-east-1
```

I need to spend some time figuring out how this works, what different environments get values wise.

**Comment by missingcharacter** [comment]
@wolfeidau Thank you for still taking a look at this. I'll spend some time pondering what it could be.

**Comment by duckfez** [comment]
I think I found the source of the `unsupported protocol scheme "urn"` message.  The SAML assertion returned by my IDP (Okta) has an `AudienceRestriction` block as so:

```
<saml2:Conditions NotBefore=\"2020-04-11T13:14:08.912Z\" NotOnOrAfter=\"2020-04-11T13:24:08.912Z\"
	xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\">
		<saml2:AudienceRestriction>
		<saml2:Audience>urn:amazon:webservices</saml2:Audience>
	</saml2:AudienceRestriction>
</saml2:Conditions>
```

The function `ExtractAudienceURL` in `saml.go` seems to be looking for `Audience` specifically and using that as the destination for posting the IDP-provided assertion to AWS.  

Maybe a better choice would be the "Destination"?  Earlier in the assertion I have:

```
<saml2p:Response Destination=\"https://signin.amazonaws-us-gov.com/saml\" ID=\"id37678891437425621029737\" IssueInstant=\"2020-04-11T13:19:08.912Z\" Version=\"2.0\"
```

I am not sure if this is something that varies from IDP to IDP.  Standards are great, there are so many to choose from!

**Comment by duckfez** [comment]
@missingcharacter my changes in #481 solve most of my problems when using Okta as an IDP.  #481 and #476 combined give me a properly working session to GovCloud **except** for my credentials file's generated stanza has a

```
region =
```

Once I fix this manually to `us-gov-east-1` then everything is 👍

**Comment by missingcharacter** [comment]
closing in favor of https://github.com/Versent/saml2aws/pull/481

**Pull request closed without merging**
